VictoireMediaBundle_media:
    resource: "@VictoireMediaBundle/Controller/MediaController.php"
    type:     annotation
    prefix:   /

VictoireMediaBundle_aviary:
    resource: "@VictoireMediaBundle/Controller/AviaryController.php"
    type:     annotation
    prefix:   /aviari

VictoireMediaBundle_media_chooser:
    resource: "@VictoireMediaBundle/Controller/ChooserController.php"
    type:     annotation
    prefix:   /

VictoireMediaBundle_media_folder:
    resource: "@VictoireMediaBundle/Controller/FolderController.php"
    type:     annotation
    prefix:   /folder
