# Add this line in your config.yml file
#imports:
#    - { resource: @VictoireTwigBundle/Resources/config/config.yml }
#
victoire_twig:
    responsive:
        xs:
            min: 0
            max: 767
        sm:
            min: 768
            max: 991
        md:
            min: 992
            max: 1199
        lg:
            min: 1200
